name: Build and Deploy Backend

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r /backend/requirements.txt # Adjust this path

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: piquecut-backend  # Replace with your Azure App Service name
          slot-name: production  # Optional: Deploy to a specific deployment slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Azure publish profile secret
          package: Piquecut/backend
